- name: Clone Dotfiles
  git:
    repo: 'https://github.com/7h3kk1d/dotfiles.git'
    dest: ~/.dotfiles
    update: yes
    recursive: yes

- name: Symlink files
  file:
    src: "~/.dotfiles/{{ item.src }}"
    dest: "~/{{ item.dest }}"
    state: link
  with_items:
    - { src: "gitconfig", dest: ".gitconfig" }
    - { src: "gitignore", dest: ".gitignore" }
    - { src: "inputrc", dest: ".inputrc" }
    - { src: "psqlrc", dest: ".psqlrc" }
    - { src: "tmux.conf", dest: ".tmux.conf" }
